/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPostsRouteImport } from './routes/_authenticated/posts'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as NSplatRouteImport } from './routes/n.$'
import { Route as UProfileIdRouteImport } from './routes/u.$profileId'
import { Route as SlugPPostIdRouteImport } from './routes/$slug.p.$postId'
import { Route as SlugPlacePlaceIdRouteImport } from './routes/$slug.place.$placeId'
import { Route as AuthenticatedAdminAccessPointsRouteImport } from './routes/_authenticated/admin.access-points'
import { Route as AuthenticatedAdminDirectoryRouteImport } from './routes/_authenticated/admin.directory'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin.members'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as AuthenticatedAdminStoreRouteImport } from './routes/_authenticated/admin.store'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesThreadIdRouteImport } from './routes/_authenticated/messages.$threadId'
import { Route as AuthenticatedPostNewRouteImport } from './routes/_authenticated/post.new'
import { Route as StoreCheckoutReturnRouteImport } from './routes/store.checkout.return'
import { Route as AuthenticatedPostPostIdEditRouteImport } from './routes/_authenticated/post.$postId.edit'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostsRoute = AuthenticatedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const NSplatRoute = NSplatRouteImport.update({
  id: '/n/$',
  path: '/n/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UProfileIdRoute = UProfileIdRouteImport.update({
  id: '/u/$profileId',
  path: '/u/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugPPostIdRoute = SlugPPostIdRouteImport.update({
  id: '/p/$postId',
  path: '/p/$postId',
  getParentRoute: () => SlugRoute,
} as any)
const SlugPlacePlaceIdRoute = SlugPlacePlaceIdRouteImport.update({
  id: '/place/$placeId',
  path: '/place/$placeId',
  getParentRoute: () => SlugRoute,
} as any)
const AuthenticatedAdminAccessPointsRoute =
  AuthenticatedAdminAccessPointsRouteImport.update({
    id: '/admin/access-points',
    path: '/admin/access-points',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDirectoryRoute =
  AuthenticatedAdminDirectoryRouteImport.update({
    id: '/admin/directory',
    path: '/admin/directory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/admin/members',
    path: '/admin/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/admin/moderation',
    path: '/admin/moderation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStoreRoute = AuthenticatedAdminStoreRouteImport.update({
  id: '/admin/store',
  path: '/admin/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesThreadIdRoute =
  AuthenticatedMessagesThreadIdRouteImport.update({
    id: '/messages/$threadId',
    path: '/messages/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostNewRoute = AuthenticatedPostNewRouteImport.update({
  id: '/post/new',
  path: '/post/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const StoreCheckoutReturnRoute = StoreCheckoutReturnRouteImport.update({
  id: '/store/checkout/return',
  path: '/store/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostPostIdEditRoute =
  AuthenticatedPostPostIdEditRouteImport.update({
    id: '/post/$postId/edit',
    path: '/post/$postId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/posts': typeof AuthenticatedPostsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/n/$': typeof NSplatRoute
  '/u/$profileId': typeof UProfileIdRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/p/$postId': typeof SlugPPostIdRoute
  '/$slug/place/$placeId': typeof SlugPlacePlaceIdRoute
  '/admin/access-points': typeof AuthenticatedAdminAccessPointsRoute
  '/admin/directory': typeof AuthenticatedAdminDirectoryRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/store': typeof AuthenticatedAdminStoreRoute
  '/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/post/new': typeof AuthenticatedPostNewRoute
  '/store/checkout/return': typeof StoreCheckoutReturnRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/post/$postId/edit': typeof AuthenticatedPostPostIdEditRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/posts': typeof AuthenticatedPostsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/n/$': typeof NSplatRoute
  '/u/$profileId': typeof UProfileIdRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/p/$postId': typeof SlugPPostIdRoute
  '/$slug/place/$placeId': typeof SlugPlacePlaceIdRoute
  '/admin/access-points': typeof AuthenticatedAdminAccessPointsRoute
  '/admin/directory': typeof AuthenticatedAdminDirectoryRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/store': typeof AuthenticatedAdminStoreRoute
  '/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/post/new': typeof AuthenticatedPostNewRoute
  '/store/checkout/return': typeof StoreCheckoutReturnRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/post/$postId/edit': typeof AuthenticatedPostPostIdEditRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRouteWithChildren
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/posts': typeof AuthenticatedPostsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/n/$': typeof NSplatRoute
  '/u/$profileId': typeof UProfileIdRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/p/$postId': typeof SlugPPostIdRoute
  '/$slug/place/$placeId': typeof SlugPlacePlaceIdRoute
  '/_authenticated/admin/access-points': typeof AuthenticatedAdminAccessPointsRoute
  '/_authenticated/admin/directory': typeof AuthenticatedAdminDirectoryRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/store': typeof AuthenticatedAdminStoreRoute
  '/_authenticated/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/_authenticated/post/new': typeof AuthenticatedPostNewRoute
  '/store/checkout/return': typeof StoreCheckoutReturnRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/post/$postId/edit': typeof AuthenticatedPostPostIdEditRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/community-guidelines'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/orders'
    | '/posts'
    | '/profile'
    | '/n/$'
    | '/u/$profileId'
    | '/$slug/'
    | '/$slug/p/$postId'
    | '/$slug/place/$placeId'
    | '/admin/access-points'
    | '/admin/directory'
    | '/admin/members'
    | '/admin/moderation'
    | '/admin/store'
    | '/messages/$threadId'
    | '/post/new'
    | '/store/checkout/return'
    | '/messages/'
    | '/post/$postId/edit'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community-guidelines'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/orders'
    | '/posts'
    | '/profile'
    | '/n/$'
    | '/u/$profileId'
    | '/$slug'
    | '/$slug/p/$postId'
    | '/$slug/place/$placeId'
    | '/admin/access-points'
    | '/admin/directory'
    | '/admin/members'
    | '/admin/moderation'
    | '/admin/store'
    | '/messages/$threadId'
    | '/post/new'
    | '/store/checkout/return'
    | '/messages'
    | '/post/$postId/edit'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/auth'
    | '/community-guidelines'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/orders'
    | '/_authenticated/posts'
    | '/_authenticated/profile'
    | '/n/$'
    | '/u/$profileId'
    | '/$slug/'
    | '/$slug/p/$postId'
    | '/$slug/place/$placeId'
    | '/_authenticated/admin/access-points'
    | '/_authenticated/admin/directory'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/store'
    | '/_authenticated/messages/$threadId'
    | '/_authenticated/post/new'
    | '/store/checkout/return'
    | '/_authenticated/messages/'
    | '/_authenticated/post/$postId/edit'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  NSplatRoute: typeof NSplatRoute
  UProfileIdRoute: typeof UProfileIdRoute
  StoreCheckoutReturnRoute: typeof StoreCheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts': {
      id: '/_authenticated/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthenticatedPostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/n/$': {
      id: '/n/$'
      path: '/n/$'
      fullPath: '/n/$'
      preLoaderRoute: typeof NSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$profileId': {
      id: '/u/$profileId'
      path: '/u/$profileId'
      fullPath: '/u/$profileId'
      preLoaderRoute: typeof UProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/p/$postId': {
      id: '/$slug/p/$postId'
      path: '/p/$postId'
      fullPath: '/$slug/p/$postId'
      preLoaderRoute: typeof SlugPPostIdRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/place/$placeId': {
      id: '/$slug/place/$placeId'
      path: '/place/$placeId'
      fullPath: '/$slug/place/$placeId'
      preLoaderRoute: typeof SlugPlacePlaceIdRouteImport
      parentRoute: typeof SlugRoute
    }
    '/_authenticated/admin/access-points': {
      id: '/_authenticated/admin/access-points'
      path: '/admin/access-points'
      fullPath: '/admin/access-points'
      preLoaderRoute: typeof AuthenticatedAdminAccessPointsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/directory': {
      id: '/_authenticated/admin/directory'
      path: '/admin/directory'
      fullPath: '/admin/directory'
      preLoaderRoute: typeof AuthenticatedAdminDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/store': {
      id: '/_authenticated/admin/store'
      path: '/admin/store'
      fullPath: '/admin/store'
      preLoaderRoute: typeof AuthenticatedAdminStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$threadId': {
      id: '/_authenticated/messages/$threadId'
      path: '/messages/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof AuthenticatedMessagesThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post/new': {
      id: '/_authenticated/post/new'
      path: '/post/new'
      fullPath: '/post/new'
      preLoaderRoute: typeof AuthenticatedPostNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/store/checkout/return': {
      id: '/store/checkout/return'
      path: '/store/checkout/return'
      fullPath: '/store/checkout/return'
      preLoaderRoute: typeof StoreCheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/post/$postId/edit': {
      id: '/_authenticated/post/$postId/edit'
      path: '/post/$postId/edit'
      fullPath: '/post/$postId/edit'
      preLoaderRoute: typeof AuthenticatedPostPostIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPostsRoute: typeof AuthenticatedPostsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminAccessPointsRoute: typeof AuthenticatedAdminAccessPointsRoute
  AuthenticatedAdminDirectoryRoute: typeof AuthenticatedAdminDirectoryRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminStoreRoute: typeof AuthenticatedAdminStoreRoute
  AuthenticatedMessagesThreadIdRoute: typeof AuthenticatedMessagesThreadIdRoute
  AuthenticatedPostNewRoute: typeof AuthenticatedPostNewRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedPostPostIdEditRoute: typeof AuthenticatedPostPostIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPostsRoute: AuthenticatedPostsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminAccessPointsRoute: AuthenticatedAdminAccessPointsRoute,
  AuthenticatedAdminDirectoryRoute: AuthenticatedAdminDirectoryRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminStoreRoute: AuthenticatedAdminStoreRoute,
  AuthenticatedMessagesThreadIdRoute: AuthenticatedMessagesThreadIdRoute,
  AuthenticatedPostNewRoute: AuthenticatedPostNewRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedPostPostIdEditRoute: AuthenticatedPostPostIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SlugRouteChildren {
  SlugIndexRoute: typeof SlugIndexRoute
  SlugPPostIdRoute: typeof SlugPPostIdRoute
  SlugPlacePlaceIdRoute: typeof SlugPlacePlaceIdRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugIndexRoute: SlugIndexRoute,
  SlugPPostIdRoute: SlugPPostIdRoute,
  SlugPlacePlaceIdRoute: SlugPlacePlaceIdRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  NSplatRoute: NSplatRoute,
  UProfileIdRoute: UProfileIdRoute,
  StoreCheckoutReturnRoute: StoreCheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
